apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: tomcat
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
        version: v1
    spec:
      containers:
      - name: tomcat
        image: image-registry.openshift-image-registry.svc:5000/test-tomcat/sample-webapp
        env:
        - name: SERVICE_NAME
          value: frontend
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: tomcat
    version: v1
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: tomcat
    version: v1
